Cargo.lock
Cargo.toml
src/backends/gstreamer/audio_stream.rs
src/backends/gstreamer/mod.rs
src/backends/gstreamer/src_element.rs
src/lib.rs

I'm not sure which one we plan to choose so both are still implemented here and not cleaned up too much.
r? @ferjm
cc @sdroege

Switch BaseSrc to AppSrc

---

build.rs
examples/android/setup.sh

This is required after moving the Android deps repo to the servo org.

Update urls for Android prebuilt dependencies

---

src/audio/block.rs
src/backends/gstreamer/audio_sink.rs

Quoting the [spec](https://webaudio.github.io/web-audio-api/#AudioScheduledSourceNode):
> Before a source is started (by calling start(), the source node MUST output silence (0). After a source has been stopped (by calling stop()), the source MUST then output silence (0).

Play silence by default

---

src/audio/destination_node.rs
src/audio/gain_node.rs
src/audio/graph.rs
src/audio/graph_thread.rs
src/audio/mod.rs
src/audio/node.rs
src/audio/oscillator_node.rs
src/audio/render_thread.rs
src/audio/sink.rs
src/backends/gstreamer/audio_sink.rs

…d tick
This is a different approach for #27.
There is one issue here that can be noticeable running the `play` example. It is supposed to play 2 seconds of two sine waves with different frequencies. With this patch the first sine wave steals most of the time of the second sine wave. I believe it is caused by the difference between the JS clock and the (currently not existent) WebAudio clock (there is a [nice blog post about this](https://www.html5rocks.com/en/tutorials/audio/scheduling/)). If that's the case this should be fixed by using the scheduling feature of AudioScheduledSourceNodes in the play example once #21 is done.

Fix audio render thread thread safety issues

---

examples/play.rs
src/audio/graph.rs
src/audio/render_thread.rs
src/audio/sink.rs
src/backends/gstreamer/audio_sink.rs

Support for BaseAudioContext.currentTime and state changes

---

src/audio/destination_node.rs
src/audio/gain_node.rs
src/audio/node.rs
src/audio/oscillator_node.rs
src/audio/render_thread.rs

We'll need this for audioparams and everything.
In the future we may need to RefCell nodes, but that's better than Cell/RefCell-ing everything inside the nodes.

Nodes are mutable

---

examples/play.rs
src/audio/block.rs
src/audio/destination_node.rs
src/audio/gain_node.rs
src/audio/mod.rs
src/audio/node.rs
src/audio/oscillator_node.rs
src/audio/param.rs
src/audio/render_thread.rs
src/backends/gstreamer/audio_sink.rs

This implements the set and ramp AudioParam events and most of the framework for the harder ones.
r? @ferjm

Implement basic AudioParams

---

examples/play.rs
src/audio/gain_node.rs
src/audio/macros.rs
src/audio/mod.rs
src/audio/node.rs
src/audio/oscillator_node.rs
src/audio/render_thread.rs
src/lib.rs

AudioScheduledSourceNode

---

Cargo.lock
Cargo.toml
examples/params.rs
examples/params_settarget.rs
examples/play.rs
src/audio/block.rs
src/audio/destination_node.rs
src/audio/gain_node.rs
src/audio/graph.rs
src/audio/graph_impl.rs
src/audio/mod.rs
src/audio/node.rs
src/audio/oscillator_node.rs
src/audio/render_thread.rs
src/backends/gstreamer/audio_sink.rs
src/lib.rs

Todo: Using it in the code
r? @ferjm

Basic graph abstraction

---

examples/Cargo.toml
examples/audio_decoder.rs
servo-media/src/audio/decoder.rs
servo-media/src/audio/graph.rs
servo-media/src/audio/mod.rs
servo-media/src/backends/gstreamer/audio_decoder.rs
servo-media/src/backends/gstreamer/mod.rs

Audio decoder

---

examples/audio_decoder.rs
servo-media/src/audio/decoder.rs
servo-media/src/audio/graph.rs
servo-media/src/backends/gstreamer/audio_decoder.rs

Addressing this review feedback https://github.com/servo/media/pull/52#discussion_r196360133

Minor decoder fixes

---

examples/Cargo.toml
examples/channels.rs
servo-media/src/audio/block.rs
servo-media/src/audio/channel_node.rs
servo-media/src/audio/destination_node.rs
servo-media/src/audio/gain_node.rs
servo-media/src/audio/graph_impl.rs
servo-media/src/audio/mod.rs
servo-media/src/audio/node.rs
servo-media/src/audio/oscillator_node.rs
servo-media/src/audio/render_thread.rs
servo-media/src/backends/gstreamer/audio_sink.rs

- Extends Block to support channels.
- Makes the DestinationNode have two channels by default. We'll later make this something that the user can set.
- Adds ChannelMergerNode
- Implements _very basic_ upmixing from one channel to multiple. Proper upmixing will come later.
Channels are stored as a continuous buffer with each FRAMES_PER_BLOCK chunk being one channel. They can also be grouped together  via `repeat` -- e.g. if an oscillator node produces 2 channels of output, it will actually produce one channel with a `repeat` bit set. Similarly, one-channel blocks will be upmixed to 2-channel `repeat` blocks.
The iterator is a bit awkward due to the lack of associated type constructors (it's a streaming iterator).
part of #18

Add basic channels abstraction, ChannelMergerNode, and sink support for channels

---

examples/audio_decoder.rs
examples/channels.rs
examples/params.rs
examples/params_settarget.rs
examples/play.rs
examples/play_noise.rs
servo-media/src/audio/graph.rs
servo-media/src/lib.rs

I identified these needs while working on the DOM bindings.
<bikeshedding>I am tempted to rename AudioGraph to AudioContext everywhere. wdyt?</bikeshedding>

Some graph API changes

---

servo-media/src/audio/block.rs
servo-media/src/audio/buffer_source_node.rs
servo-media/src/audio/channel_node.rs
servo-media/src/audio/destination_node.rs
servo-media/src/audio/gain_node.rs
servo-media/src/audio/graph.rs
servo-media/src/audio/node.rs
servo-media/src/audio/oscillator_node.rs
servo-media/src/backends/gstreamer/audio_sink.rs

- Adds channel count modes
- Adds channel interpretation modes
- Adds all the upmix/downmix equations
Haven't yet written tests for this partially because I don't have quad/5.1 systems to test with.
r? @ferjm

Channel fixes

---

examples/channels.rs
servo-media-derive/src/lib.rs
servo-media/src/audio/block.rs
servo-media/src/audio/buffer_source_node.rs
servo-media/src/audio/channel_node.rs
servo-media/src/audio/destination_node.rs
servo-media/src/audio/gain_node.rs
servo-media/src/audio/graph.rs
servo-media/src/audio/macros.rs
servo-media/src/audio/node.rs
servo-media/src/audio/oscillator_node.rs
servo-media/src/audio/render_thread.rs
servo-media/src/backends/gstreamer/audio_sink.rs

I'm trying a trait based trick for keeping message handling common. If you like this
we can use something similar for AudioScheduledSourceNode.
This is also used by the sink, and the example merges channels halfway through by forcing a mix on the sink.
based off #60
r? @ferjm

Add support for setting channel information

---

servo-media/src/backends/gstreamer/audio_sink.rs

With this patch I can notice a much lower latency running the theremin demo.
r? @Manishearth @sdroege

Reduce latency by setting appsrc max-bytes to the block size

---

.cargo/config
servo-media/src/audio/graph.rs

(part of #68)
We currently have the edges going in the reverse direction as the audio,
which is confusing. The reason we did this was so that we could use the
DFSPostOrder iterator.
This inverts their direction so that edges now go from source to sink, and
uses a `Reversed` adaptor to fix it.
r? @ferjm

Invert edge direction

---

servo-media/src/audio/decoder.rs
servo-media/src/lib.rs

This avoids having to do a bunch of clones on the caller side. Not strictly necessary, but it's cleaner.

Use FnOnce for final decoder callbacks

---

examples/android/lib/src/lib.rs
examples/audio_decoder.rs
examples/channels.rs
examples/channelsum.rs
examples/params.rs
examples/params_settarget.rs
examples/play.rs
examples/play_noise.rs
servo-media/src/audio/buffer_source_node.rs
servo-media/src/audio/channel_node.rs
servo-media/src/audio/context.rs
servo-media/src/audio/destination_node.rs
servo-media/src/audio/gain_node.rs
servo-media/src/audio/graph.rs
servo-media/src/audio/node.rs
servo-media/src/audio/oscillator_node.rs
servo-media/src/audio/param.rs
servo-media/src/audio/render_thread.rs

This adds a ParamType that lets us talk about AudioParams in a unified way. From the DOM side an `AudioParam` can now just be a `(NodeId, ParamType)` pair.
In the future we can use this to talk of connecting nodes to audio params as well, as an variant of PortId.
I also did some cleanups, marking engine-related things crate-public (script should never create engines), and renaming `AudioNodeType` to `AudioNodeInit` (this will require a rename in the DOM code) to better reflect what it does. `AudioNodeType` now exists as a bare enum for debugging purposes.
r? @ferjm

Unify setparam methods, various cleanups

---

examples/Cargo.toml
servo-media/Cargo.toml
servo-media/src/audio/context.rs
servo-media/src/audio/render_thread.rs
servo-media/src/backends/dummy/audio_decoder.rs
servo-media/src/backends/dummy/audio_sink.rs
servo-media/src/backends/dummy/mod.rs
servo-media/src/backends/mod.rs
servo-media/src/lib.rs

This should help us land the WebAudio API in Servo without Android support.

Dummy backend

---

audio/src/block.rs
audio/src/graph.rs
audio/src/lib.rs
audio/src/param.rs
audio/src/render_thread.rs
examples/Cargo.toml
examples/params_connect.rs

Since the AudioListener stuff is in flux I figured I'd get this out of the way. Was pretty straightforward.
Todo: Fill in `disconnect()` impls for this
r? @ferjm

Add support for connecting nodes to params

---

audio/src/context.rs
audio/src/lib.rs
audio/src/offline_context.rs
audio/src/offline_sink.rs
audio/src/render_thread.rs
audio/src/sink.rs
backends/gstreamer/src/audio_sink.rs
examples/Cargo.toml
examples/offline_context.rs

I made the new offline context implement the existing AudioSink trait so we can reuse the current render thread processing algorithm.
r? @Manishearth

Support for offline context

---

Cargo.lock
Cargo.toml
audio/Cargo.toml
audio/src/lib.rs
backends/gstreamer/Cargo.toml
backends/gstreamer/src/lib.rs
backends/gstreamer/src/player.rs
examples/Cargo.toml
examples/player.rs
player/Cargo.toml
player/src/frame.rs
player/src/lib.rs
player/src/metadata.rs
servo-media/Cargo.toml
servo-media/src/lib.rs

This pull request is rebased above #87

Add Player as a crate

---

servo-media/Cargo.toml
servo-media/src/lib.rs

We don't have the ability to include it as a dependency on our CI right now.

Turn off gstreamer for non-x86

---

.gitignore
Cargo.lock
Cargo.toml
examples/android/lib/Cargo.toml
examples/android/lib/src/lib.rs
examples/android/run.sh

Fix Android example

---

Cargo.lock
audio/src/lib.rs
backends/gstreamer/Cargo.toml
backends/gstreamer/src/lib.rs
backends/gstreamer/src/player.rs
examples/Cargo.toml
examples/player/main.rs
player/Cargo.toml
player/src/lib.rs
player/src/metadata.rs
servo-media/src/lib.rs

the first two commits are simple fixes to the code.
4bfa467 moves the init() function into a shared one between the audio and the player. This is a RFC, since perhaps it  can be defined as a trait. I'm not sure
7d28b6a it is required to pass the event messages through the ROUTER in servo

fixes, init and change to use ipc crate

---

README.md

I don't think this anchor is still used. I accidentally left it in in my previous edit.

Remove unused anchor link

---

Cargo.lock
backends/gstreamer/Cargo.toml

This completely remove an unused dependency from backends/gstreamer and fixes this build error:
```
error: failed to parse lock file at: /Users/ferjm/dev/mozilla/media/Cargo.lock
Caused by:
package `num-traits 0.1.43 (registry+https://github.com/rust-lang/crates.io-index)` is specified as a dependency, but is missing from the package list
```
r? @ceyusa

Remove unused num-traits and fix lock

---

Cargo.lock
audio/Cargo.toml
audio/src/block.rs
audio/src/context.rs
audio/src/graph.rs
audio/src/lib.rs
audio/src/listener.rs
audio/src/node.rs
audio/src/panner_node.rs
audio/src/param.rs
audio/src/render_thread.rs
examples/Cargo.toml
examples/panner.rs

This adds support for AudioListener and AudioPanner
I haven't tested it yet, but it's ready for preliminary review.

Add AudioListener and PannerNode support

---

audio/src/decoder.rs
backends/gstreamer/src/audio_decoder.rs
examples/audio_decoder.rs

Deinterleave decoded audio

---

audio/src/buffer_source_node.rs
audio/src/channel_node.rs
audio/src/context.rs
audio/src/gain_node.rs
audio/src/node.rs
audio/src/oscillator_node.rs
audio/src/panner_node.rs
audio/src/render_thread.rs
examples/android/lib/src/lib.rs
examples/audio_decoder.rs
examples/channels.rs
examples/channelsum.rs
examples/offline_context.rs
examples/panner.rs
examples/params.rs
examples/params_connect.rs
examples/params_connect2.rs
examples/params_settarget.rs
examples/play.rs
examples/play_noise.rs

The constructors get to set these. Many nodes have additional constraints but these constraints are implemented by the DOM.
r? @ferjm

Pass down ChannelInfo for nodes

---

Cargo.lock
audio/Cargo.toml
audio/src/analyser_node.rs
audio/src/block.rs
audio/src/lib.rs
audio/src/node.rs
audio/src/render_thread.rs

Do not merge yet, I need to ensure it works on the servo side.
r? @ferjm

Implement AnalyserNode

---

audio/src/panner_node.rs

|| short-circuits, so not all parameters will update

Use |= instead of || for update_parameters

---

audio/src/biquad_filter_node.rs
audio/src/block.rs
audio/src/gain_node.rs
audio/src/lib.rs
audio/src/node.rs
audio/src/oscillator_node.rs
audio/src/param.rs
audio/src/render_thread.rs
examples/Cargo.toml
examples/biquad.rs

This contains all the code BiquadFilterNode should need, but I haven't had a chance to test it yet.
However, there are lots of equations here, so I thought I'd post it early to get a head start on review.
Note that for the actual processing code I'm using the formula from https://github.com/WebAudio/web-audio-api/pull/1758 .
r? @ferjm

Implement BiquadFilterNode

---

.travis.yml

I've regenerated the binaries for Trusty to include the missing plugins, so we shouldn't need to install the system `gstreamer1.0-plugins-base` dep.

Do not install old distro gstreamer-plugins-base on CI

---

backends/gstreamer/src/player.rs

This is intermittently failing, but we are not seeking yet, so we don't need to do this for now.

Do not disable periodic position updates

---

audio/src/biquad_filter_node.rs
audio/src/block.rs
audio/src/buffer_source_node.rs
audio/src/node.rs
audio/src/oscillator_node.rs
audio/src/param.rs
servo-media-derive/src/lib.rs

Fixes https://github.com/servo/media/issues/147
This fixes almost all the biquad failures, as well as some analyser node and buffer node failures.
More information for why the fix was necessary can be found in the individual commit messages
r? @ferjm

Various bugfixes

---

backends/gstreamer/src/audio_decoder.rs

Each appsink will signal eos individually and considering the first
one's eos as the global end-of-stream might cause the pipeline to be
shut down before all other appsinks are done processing their data.
The Eos message on the bus is only sent once *all* sinks are
end-of-stream.
Fixes https://github.com/servo/media/issues/151
----
Untested but should fix the race condition. I've also added the line to send something to the mpsc sender because a few lines below a comment claims that we `// Wait until we get an error or EOS.`, and only the error cases were covered.

Wait for Eos message on the bus for signalling global end-of-stream

---

backends/gstreamer/src/player.rs
examples/player/main.rs
examples/simple_player.rs
player/src/lib.rs

This is required to implement the details of https://html.spec.whatwg.org/multipage/media.html#offsets-into-the-media-resource

[Player API] Expose media timeline data

---

servo-media/Cargo.toml
servo-media/src/lib.rs

We're only supporting gstreamer on x86 and arm32 android, not arm64 android.

Don't require gstreamer on aarch64 android

---

.gitignore

Otherwise this silently ignores any new files under backends/gstreamer, which is not what we want.

Only ignore gstreamer dir in root directory.

---

backends/gstreamer/src/lib.rs
backends/gstreamer/src/player.rs

Check that we have the required elements to instantiate a gst-player

---

backends/gstreamer/src/player.rs

Queue a/v data while player is setting up

---

Cargo.lock
backends/gstreamer/Cargo.toml
backends/gstreamer/src/lib.rs
backends/gstreamer/src/player.rs
examples/Cargo.toml
player/Cargo.toml

* Some cleanups to avoid multiple versions of some dependencies
* Use VideoFrame from gstreamer-video (adding a new dependency). Also, If I understand correctly, this will save a copy of the frame.

some cleanups and use videoframe API

---

backends/gstreamer/src/player.rs

r? @ceyusa 
As we discussed in person, we are already blocking on the Player setup before allowing to push any data, so there's really no need for a data queue.

Revert "Queue a/v data while player is setting up"

---

backends/gstreamer/src/player.rs
examples/player/main.rs
examples/simple_player.rs
player/src/lib.rs

There is no way the playback rate can change unless the client changes it through the API, so this event is useless and unfortunately the cause of a deadlock.

Remove RateChanged player event

---

audio/src/context.rs
audio/src/decoder.rs
audio/src/lib.rs
audio/src/offline_sink.rs
audio/src/render_thread.rs
audio/src/sink.rs
backends/gstreamer/src/audio_decoder.rs
backends/gstreamer/src/audio_sink.rs
backends/gstreamer/src/lib.rs
backends/gstreamer/src/player.rs
examples/player/main.rs
examples/simple_player.rs
player/src/lib.rs
servo-media/src/lib.rs

This PR exposes the `EnoughData` and `NeedData` Player events that allow consumers to implement a backoff protocol.
I made a couple of significant refactors:
- I moved the list of Player observers and renderers out of `PlayerInner` to avoid deadlocks. For more information, you can read [this IRC conversation](https://mozilla.logbot.info/servo-media/20181219#c15742907-c15743272).
- I had to change the way we report errors in general to allow external consumption.

Expose a way to implement a backoff protocol, refactor errors and other minor improvements

---

backends/gstreamer/src/audio_decoder.rs
backends/gstreamer/src/audio_sink.rs
backends/gstreamer/src/player.rs

The current way to get the error description will fail in the next version of glib.

use ToString trait to get GLib error description

---

backends/gstreamer/src/player.rs

We need an init flag per Player instance, not a global flag. Regarding [this question](https://github.com/servo/media/pull/176#discussion_r244247665) I believe the usage of `Ordering::Relaxed` is fine here as it is harmless to send the unlock message twice.

Use a Once per Player init

---

examples/player/main.rs
examples/player/player_wrapper.rs
examples/player/ui.rs

In order to configure the test player to use GL rendering, it's required to pass GL parameters from the application to the player, before its configuration. Because of that the player must be instantiated after the UI is launched.
This PR does this.
I think it's better to merge it soon in order to avoid more complex rebases later :)

Decouple playerwrapper for player test

---

Cargo.lock
Cargo.toml
backends/gstreamer/Cargo.toml
backends/gstreamer/src/lib.rs
backends/gstreamer/src/media_capture.rs
backends/gstreamer/src/media_stream.rs
backends/gstreamer/src/webrtc.rs
examples/Cargo.toml
examples/simple_webrtc.rs
servo-media/Cargo.toml
servo-media/src/lib.rs
webrtc/Cargo.toml
webrtc/src/lib.rs
webrtc/src/thread.rs

This adds a WebRtcController abstraction that can be used directly from DOM, along with a Gstreamer backend implementation for it.
We don't yet have a good automated test for this functionality.
r? @jdm @ferjm

Merge in webrtc work

---

backends/gstreamer/src/lib.rs
backends/gstreamer/src/media_stream.rs
backends/gstreamer/src/webrtc.rs
examples/simple_webrtc.rs
servo-media/src/lib.rs
webrtc/src/lib.rs
webrtc/src/thread.rs

There should be no difference in behaviour as a result of these changes. They fix https://github.com/jdm/media/issues/6.

Add remote stream callback and simple abstraction for playback.

---

Cargo.lock
backends/gstreamer/src/audio_decoder.rs
backends/gstreamer/src/lib.rs
backends/gstreamer/src/media_capture.rs
backends/gstreamer/src/media_stream.rs
backends/gstreamer/src/player.rs
backends/gstreamer/src/webrtc.rs
examples/Cargo.toml
examples/player/main.rs
player/src/frame.rs

This pull request is a preparation for the video frames rendering as gl textures in the player example:
* isolate the video sinks setup in a function
* add gst logging capabilities to gstreamer player backend, rather than use print macros
* specify a specific commit id to webrender, since we are using git head, but an update will break our example app
* use glib and gstreamer preludes, this is a general clean up recommended by @sdroege 
* the player example eats all the available memory since a great big image leak
* instead of keeping a vector with pushed frames from player example, add a custom queue with only three frames
* as we are using Arc'ed data, there's no need to return a reference

Clean up and misc fixes

---

.travis.yml

Now Travis support Ubuntu Xenial with updated version of package dependencies.
A new GStreamer bundle was generated with current master with a closer track to runtime dependencies.

Update distro to Xenial and GStreamer bundle

---

Cargo.lock
backends/gstreamer/Cargo.toml
backends/gstreamer/src/audio_decoder.rs
backends/gstreamer/src/audio_sink.rs
backends/gstreamer/src/lib.rs
backends/gstreamer/src/media_capture.rs
backends/gstreamer/src/media_stream.rs
backends/gstreamer/src/player.rs
backends/gstreamer/src/source.rs
backends/gstreamer/src/webrtc.rs
examples/Cargo.toml
examples/player/main.rs
examples/player/player_wrapper.rs
examples/player/ui.rs
player/src/frame.rs
player/src/lib.rs

This PR goes above PR https://github.com/servo/media/pull/196
It needs to update the CI GStreamer setup, because it requires  a new version of glib and gstreamer-gl library.
It contains
* Port to webrender 0.58 
* Port to gstreamer git head version (0.13.0) -- this implied a complete rewrite of servosrc
* Add a new trait in Frame to hold a reference to the backend's buffer
* Update glutin version tu current git head
* Add a method to set the GL parameters in the backend's player
* Use glsinkbin in gstreamer player in GL parameters are negotiated
* A lot of changes in example player to render gl textures is --gl argument is passed
Fixes: https://github.com/servo/media/issues/166

Negotiate  GL textures and render them in player example

---

backends/gstreamer/src/player.rs
examples/player/player_wrapper.rs
examples/simple_player.rs
player/src/lib.rs

This should allow us to fix issues like https://github.com/servo/servo/issues/22931

Player shutdown

---

backends/gstreamer/src/media_capture.rs
backends/gstreamer/src/media_stream.rs
backends/gstreamer/src/webrtc.rs
examples/simple_webrtc.rs

fixes https://github.com/servo/media/issues/191

Make sink code work again

---

Cargo.lock
backends/dummy/src/lib.rs
backends/gstreamer/Cargo.toml
backends/gstreamer/src/media_capture.rs
backends/gstreamer/src/media_stream.rs
backends/gstreamer/src/webrtc.rs
examples/simple_webrtc.rs
webrtc/src/lib.rs
webrtc/src/thread.rs

Fixes #210
Based on #208
This implements a version of the fix detailed in https://github.com/servo/media/issues/210#issuecomment-467365523
Instead of unlinking/relinking, we simply keep new streams unlinked until we decide to trigger an offer, at which point we link them to new request pads. The answerer side keeps them unlinked until it gets a remote offer, at which point it also requests pads and links them to the correctly numbered request pads.
A missing piece was that the payload number also has to match, so we keep track of that too.
r? @jdm @slomo (last two commits only)

Fix sink pad ordering

---

Cargo.lock
backends/dummy/src/lib.rs
backends/gstreamer/src/lib.rs
backends/gstreamer/src/webrtc.rs
webrtc/Cargo.toml
webrtc/src/lib.rs
webrtc/src/thread.rs

fixes https://github.com/servo/media/issues/206

Add proper Webrtc error type

---

Cargo.lock
backends/dummy/src/lib.rs
backends/gstreamer/src/lib.rs
backends/gstreamer/src/webrtc.rs
webrtc/Cargo.toml
webrtc/src/lib.rs
webrtc/src/thread.rs

based on #215 (but largely independent, this is only to avoid merge conflicts later)
fixes #216
r? @jdm

Add signaling, gathering, and ICE connection state callbacks

---

backends/gstreamer/src/webrtc.rs
webrtc/src/thread.rs

It is possible for link_streams to be called when our code has received a remote offer (and thus `remote_mline_info` is set), but before `set-remote-description` has completely finished executing. This can lead to `link_streams` _thinking_ that the webrtcbin is ready to create new pads, while the internal transceivers haven't yet been created. Thus even though we link streams to the appropriate pads, the transceivers are created in the wrong order, and some of the gstreamer code looks at transceiver creation order instead of mline info (this is a bug), breaking things.
fixes ##225
r? @jdm

Avoid race between set-remote-description and link_streams

---

audio/param.rs
examples/Cargo.toml
examples/set_value_curve.rs

fixes https://github.com/servo/media/issues/204

 Implemented SetValueCurveAtTime

---

Cargo.lock
Cargo.toml
backends/gstreamer/Cargo.toml
backends/gstreamer/lib.rs
backends/gstreamer/player.rs
backends/gstreamer/render-unix/Cargo.toml
backends/gstreamer/render-unix/lib.rs
backends/gstreamer/render.rs
backends/gstreamer/render/Cargo.toml
backends/gstreamer/render/lib.rs
examples/Cargo.toml
examples/player/player_wrapper.rs
examples/player/ui.rs

This PR creates two new crates inside gstreamer backend:
- A render crate which only defines a trait for different renders  for different OS 
- A render object helper that will setup the rendering bits for the player
- A unix-render crate which implementes the render trait for Unix-based GL systems
This will fix the problem with cargo with features per target.
It is not well tested yet. And the GL implementation still has some missing bits.
I would like to propose a new create depending on glutin to extract the GL context and display for different platforms used by the possible gl renders.

 Render crates

---

Cargo.lock
backends/dummy/lib.rs
backends/gstreamer/Cargo.toml
backends/gstreamer/lib.rs
backends/gstreamer/registry_scanner.rs
servo-media/lib.rs

This is related to https://github.com/servo/servo/issues/22299. I tried to follow WebKit's [implementation](https://github.com/WebKit/webkit/blob/ae5a8bdded113530fe844e01ad9c0e72ce85dbe2/Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.cpp#L304) of a similar function, as suggested by @ferjm in the issue's comments.

Implement can_play_type for ServoMedia

---

Cargo.lock
backends/gstreamer/Cargo.toml
backends/gstreamer/lib.rs
backends/gstreamer/player.rs
backends/gstreamer/source.rs
examples/play_media_stream.rs
examples/player/player_wrapper.rs
examples/simple_player.rs
player/lib.rs

Seeking requires a strict handling of each buffer offset. Though appsrc do some offset handling, but only for live stream (not seeking). When random-access is enabled the application must take care of marking each buffer offset correctly.
This patch extends servosrc's method push_buffer() so it will count the current offset and stamps it on the pushed buffer. Also, it honors the buffer's block size defined in appsrc, splitting the input data in several buffers if it's bigger, fixing some problems with the buffering mechanism in playbin.
When a seek operation is done, the current media offset must be updated with the requested position.
As per media/player design, it is required that the user must push synchronized the data from the requested position by the seek.

Handle buffer offset in servosrc

---

audio/lib.rs
audio/node.rs
audio/panner_node.rs
audio/param.rs
audio/render_thread.rs
audio/stereo_panner.rs
examples/Cargo.toml
examples/stereo_panner.rs

Implemented the backend for StereoPannerNode in the media crate by creating a new node implementation using PannerNode as a guide according to the specification.

StereoPannerNode backend

---

backends/dummy/lib.rs
backends/gstreamer/lib.rs
backends/gstreamer/player.rs
backends/gstreamer/render-unix/lib.rs
backends/gstreamer/render.rs
examples/play_media_stream.rs
examples/player/player_wrapper.rs
examples/player/ui.rs
examples/simple_player.rs
player/context.rs
player/lib.rs
servo-media/lib.rs

PlayerGLContext will provide the GL context paratemers required to
create a Render object. If those parameters are supported by the
Render, it will setup a GL rendering pipeline and will handle the
frames in form of GL Textures.
The PlayerGLContext is passed to the player at its instantiation.

Add trait PlayerGLContext

---

backends/gstreamer/webrtc.rs

fixes https://github.com/servo/media/issues/249
r? @jdm or @ferjm

Don't reentrantly lock the stream id

---

backends/dummy/lib.rs
backends/gstreamer/player.rs
examples/player/main.rs
examples/player/player_wrapper.rs
examples/player/ui.rs
player/lib.rs

This is the media player side for https://github.com/servo/servo/issues/23336

Add API for disabling video track

---

player/context.rs

Fixes: #251
As far as I have played, there's no need to make PlayerGLContext trait thread aware, so we could avoid the changes in https://github.com/servo/media/pull/253

PlayerGLContext does not need to be thread aware

---

backends/gstreamer/lib.rs
servo-media/lib.rs

This should be enough to get some of the webrtc tests running on CI.
This doesn't capsfilter, so we may get test failures due to that.
r? @jdm @ferjm

Add support for simple media capture mocking

---

audio/param.rs

Fixes https://github.com/servo/servo/issues/22580

Fix panic on "unreachable code" that is reachable

---

audio/analyser_node.rs
audio/context.rs
audio/decoder.rs
audio/graph.rs
audio/lib.rs
audio/node.rs
audio/offline_sink.rs
audio/render_thread.rs
audio/sink.rs
backends/dummy/lib.rs
backends/gstreamer/audio_sink.rs
backends/gstreamer/lib.rs
backends/gstreamer/media_stream.rs
backends/gstreamer/player.rs
backends/gstreamer/render-unix/lib.rs
backends/gstreamer/render.rs
backends/gstreamer/webrtc.rs
examples/player/main.rs
examples/player/player_wrapper.rs
examples/player/ui.rs
examples/simple_webrtc.rs
player/frame.rs
servo-media/lib.rs
streams/lib.rs
streams/registry.rs
webrtc/lib.rs
webrtc/thread.rs

Current nightly compiler shows as warning when a trait object is wrapped by Box, Arc or Mutex, which is recommended in the documentation. 
This patch add the clause to all reported cases.

Add dyn clause when using trait object

---

backends/gstreamer/player.rs
backends/gstreamer/render-unix/lib.rs
examples/play_media_stream.rs
examples/player/main.rs
examples/player/ui.rs
examples/simple_player.rs
player/context.rs
player/frame.rs

These patches add trait methods required to reach the GL rendering in servo and a couple fixes for logging in GStreamer.

Traits methods and logs

---

Cargo.lock
backends/gstreamer/Cargo.toml
backends/gstreamer/webrtc.rs

Upstream had [a bug](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/issues/189) which we worked around in https://github.com/servo/media/pull/213 by directly accessing the underlying GObject data. This is no longer necessary after the gstreamer update, pulling in https://github.com/servo/media/pull/213
r? @sdroege @ferjm

Get rid of unsafe SDP media workaround

---

backends/gstreamer/lib.rs
servo-media/lib.rs

This is necessary to support initializing GStreamer with the correct plugins in binary distributions for consumers that don't already have GStreamer installed.

Support initializing backend separately from media stack.

---

audio/lib.rs
audio/node.rs
audio/render_thread.rs
audio/wave_shaper_node.rs
examples/Cargo.toml
examples/wave_shaper.rs

Issue at hand: servo/media#205

WaveShaper node implementation without oversampling

---

Cargo.lock
examples/Cargo.toml
examples/player/main.rs

Issue #259.
I'm not sure if `--no-video` and `--gl` help strings are valid though.

delegate player example args parsing to clap

---

backends/gstreamer/player.rs
backends/gstreamer/source.rs
examples/muted_player.rs
examples/play_media_stream.rs
examples/player/app.rs
examples/simple_player.rs
player/lib.rs

These pull request includes:
* Fix a bug in player test app to filter the key press from the window
* Duplicate the size of input buffers in the player test to reduce the buffering
* Mute/unmute the player test when 'm' is pressed
* Block the player until the application finish the seek task, this is important to avoid download element get lost
* Handle the requested offset in servo source (kind of a continuation of the player blocking at seek)
With these changes, at least theoretically, we could revert commit 56fe008

Block seek

---

.travis.yml
backends/gstreamer/Cargo.toml
backends/gstreamer/render-unix/Cargo.toml
backends/gstreamer/render-unix/lib.rs
examples/Cargo.toml

These two patches add
* Split the different dependencies for samples, keeping a control of which dependencies are required by which examples.
* Added a GL winsys feature, for unix render, so it can modified for different CI

Add feature handling

---

Cargo.toml
audio/context.rs
backends/dummy/lib.rs
backends/gstreamer/lib.rs
backends/gstreamer/player.rs
examples/Cargo.toml
examples/muted_audiocontext.rs
examples/muted_player.rs
examples/play_media_stream.rs
examples/player/app.rs
examples/simple_player.rs
examples/wave_shaper.rs
player/lib.rs
servo-media/lib.rs
traits/lib.rs

This is a cleaner approach that does not require consumers of the API to call any shutdown* method to ensure that the Muteables are removed appropriately.

Remove shutdown_player and shutdown_audio_context

---

audio/block.rs
audio/buffer_source_node.rs
examples/audio_decoder.rs
examples/offline_context.rs
examples/play_noise.rs

This is most of the fix for [Servo's #22363](https://github.com/servo/servo/issues/22363). It is broken into four pieces. Let me know if I can help in the reviewing process.

Implement missing functionality of AudioBufferSourceNode

---

backends/dummy/lib.rs
backends/gstreamer/player.rs
player/lib.rs

This pull request is for being able to set video and audio tracks and is part of Servo issue [22799](https://github.com/servo/servo/issues/22799). 
Servo should be able to set multiple audio tracks at one time but the work here only allows for one. If anyone has any advice on how to set multiple audio tracks that would be great!

Updated player for setting audio and video tracks

---

Cargo.lock
backends/gstreamer/Cargo.toml
backends/gstreamer/render-android/Cargo.toml
backends/gstreamer/render-android/lib.rs
backends/gstreamer/render-unix/lib.rs
backends/gstreamer/render.rs

Add GL render for android target, which is a unix type with only EGL.

Render android

---

backends/gstreamer/render-android/lib.rs

Sync the GL video frames on the renderer's GL context rather than the app's GL context.

Sync each frame on the renderer's GL context not the app context

---

audio/buffer_source_node.rs
audio/context.rs
backends/dummy/lib.rs
backends/gstreamer/lib.rs
backends/gstreamer/player.rs
examples/audio_decoder.rs
servo-media/lib.rs
traits/lib.rs

This is required for fixing https://github.com/servo/servo/issues/22763 and https://github.com/servo/servo/issues/21989
ServoMedia shuts down AudioContexts and Players when these are dropped, but because Servo keeps a bfcache, DOM objects are not always released immediately after navigation. So we need a way to manually suspend playback.
A similar issue occurs with `getUserMedia`, where we keep input streams active after navigation. I'll fix it in a follow-up.

Expose methods to suspend and resume all media actions

---

examples/player/context.rs

If EGLDisplay is used in a Wayland environment is incorrect, since
gstreamer will instanciate a dummy window not a wayland surface.

Try first wayland and x11 displays before egl

---

backends/gstreamer/audio_decoder.rs

We are hiding useful information unnecessarily.

Better error messages for audio decoder linking failures.

---

audio/buffer_source_node.rs
audio/panner_node.rs

issue #300 
running test https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/webaudio/the-audio-api/the-audiobuffersourcenode-interface/buffer-resampling.html after this patch results in:

linear extrapolation of endpoint samples in AudioBufferSourceNode

---

Cargo.lock
audio/Cargo.toml
audio/lib.rs
audio/wave_shaper_node.rs
examples/wave_shaper.rs

Issue #205 
Finally managed to defeat the noise I mentioned in the issue 
I'm not sure if ditching FrameIterator and operating on raw vecs was a good thing :man_shrugging: 
Also spec mentions tail-time but I'm not sure how to handle that

2x and 4x oversampling for WaveShaperNode

---

backends/gstreamer/registry_scanner.rs
backends/gstreamer/render/lib.rs

also fixed unused-extern-crates warning
GStreamerRegistryScanner was checking if wav is supported by searching
gstreamer factories for application/x-wav caps, but some hosts report wav
mime as audio/x-wav.
issue: https://github.com/servo/servo/issues/26273

added demuxer presence check for audio/x-wav media type

---

audio/node.rs

since its needed to compare AudioNodeTypes on AutomationRate change

implemented Eq on AudioNodeType

---

Cargo.lock
audio/Cargo.toml
audio/graph.rs
audio/lib.rs
audio/media_stream_destination_node.rs
audio/node.rs
audio/offline_sink.rs
audio/render_thread.rs
audio/sink.rs
backends/dummy/lib.rs
backends/gstreamer/audio_sink.rs
backends/gstreamer/player.rs
backends/gstreamer/source.rs
examples/Cargo.toml
examples/stream_dest_node.rs
streams/lib.rs

One suboptimal part is that currently you need to block on a receiver to get the media stream id.
There are a couple better ways to do that:
- Pass in the AudioSink from the client
- Tweak the streams api to allow creating a media stream that has no input yet, and connect it up to
Fixes #342 
Thoughts?

Add MediaStreamDestinationNode

---

Cargo.lock
backends/dummy/lib.rs
backends/gstreamer/datachannel.rs
backends/gstreamer/lib.rs
backends/gstreamer/player.rs
backends/gstreamer/source.rs
backends/gstreamer/webrtc.rs
examples/simple_webrtc.rs
webrtc/Cargo.toml
webrtc/datachannel.rs
webrtc/lib.rs
webrtc/thread.rs

This is not entirely spec compliant, but it contains the basic stuff to make data channels work. It allows sending only strings for now.

WebRTC data channels backend

---

backends/gstreamer/media_capture.rs
backends/gstreamer/media_stream.rs
backends/gstreamer/webrtc.rs

This fixes https://github.com/servo/media/issues/354 by normalizing all streams to contain raw audio. Instead, webrtc is given a way to obtain an encoded adapter for a given media stream.
Fixes #354

Separate out encoding of media streams

---

backends/gstreamer/lib.rs
backends/gstreamer/player.rs
player/video.rs
webrtc/lib.rs

Addresses the following warn-by-default lints, which are reported by the current compiler:
- `stable_features` (feature `nll`)
- `semicolon_in_expressions_from_macros`
- `anonymous_parameters`
- `dead_code`

refactor: address lints

---

webrtc/lib.rs

The fn_traits nightly feature isn't used anywhere.

Support building on stable

---

Cargo.lock
backends/dummy/Cargo.toml
backends/gstreamer/Cargo.toml
examples/Cargo.toml
player/Cargo.toml

ipc-channel used in servo needs to bumped to 0.16.1 to complete https://github.com/servo/servo/issues/29467, but that requires the same version to be used by media crates as well.
FYI: I had accidentally pushed my change to master branch of this repo. I've now force pushed master to it's previous state. I've also made 'master' a protected branch. Please let me know if that needs to be changed or removed.

Update ipc-channel to 0.16

---

.github/workflows/rust.yml
Cargo.lock

- Fix the build on the latest nightly by bumping proc-macro-2.
- Disable the examples during CI run, which seem to have bitrotted.

Enable the GitHub merge queue

---

Cargo.lock
backends/gstreamer/Cargo.toml

These build dependencies are being incorporated into Servo and they are
completely unused.

Clean up dependencies and remove unused build deps

---

Cargo.lock
streams/Cargo.toml
webrtc/Cargo.toml

This will allow Servo to dedup the uuid crate.

Update uuid to 1.4

---

servo-media/Cargo.toml
servo-media/lib.rs

Move initialization of the media engine to a background thread. This
also replaced the complex INITIALIZER / INSTANCE combo with a single
synchronous `OnceCell`. Finally, instead of taking in the `Backend` as
an argument, take in a factory function. This allows the `Backend` to
also be initialized off the main thread.
This allows GStreamer plugin cache initialization to happen off the main
thread and removes unsafe code in initialization.
Co-authored-by: Rakhi Sharma <atbrakhi@igalia.com>

Initialize media in the background

---

Cargo.lock
backends/gstreamer/Cargo.toml
backends/gstreamer/lib.rs

This is a workaround for an issue where GStreamer does not deliver end
of stream signals unless there is a main loop running. See [1] for
more information.
1. https://github.com/servo/media/pull/393#issuecomment-1813934250
Co-authored-by: Víctor Manuel Jáquez Leal <vjaquez@igalia.com>

Run a glib main loop for the GStreamer backend

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
appveyor.yml
backends/auto/Cargo.toml
backends/auto/lib.rs
backends/gstreamer/Cargo.toml
backends/gstreamer/audio_decoder.rs
backends/gstreamer/audio_sink.rs
backends/gstreamer/audio_stream_reader.rs
backends/gstreamer/datachannel.rs
backends/gstreamer/device_monitor.rs
backends/gstreamer/lib.rs
backends/gstreamer/media_capture.rs
backends/gstreamer/media_stream.rs
backends/gstreamer/media_stream_source.rs
backends/gstreamer/player.rs
backends/gstreamer/registry_scanner.rs
backends/gstreamer/render-android/Cargo.toml
backends/gstreamer/render-android/lib.rs
backends/gstreamer/render-unix/Cargo.toml
backends/gstreamer/render-unix/lib.rs
backends/gstreamer/render.rs
backends/gstreamer/render/Cargo.toml
backends/gstreamer/render/lib.rs
backends/gstreamer/source.rs
backends/gstreamer/webrtc.rs
examples/android/lib/src/lib.rs
examples/player/context.rs
webrtc/datachannel.rs

I've upgraded the version of the GStreamer Rust bindings. I've tried to make the minimal possible changes to the code, keeping all previous logic and behavior.
Please let me know if I've missed anything.

Upgrade GStreamer dependencies and switch to Rust 2021 edition

---

backends/auto/Cargo.toml
backends/dummy/Cargo.toml
backends/gstreamer/Cargo.toml
backends/gstreamer/render-android/Cargo.toml
backends/gstreamer/render-unix/Cargo.toml
backends/gstreamer/render/Cargo.toml
examples/android/lib/Cargo.toml
servo-media-derive/Cargo.toml
servo-media/Cargo.toml
streams/Cargo.toml
traits/Cargo.toml
webrtc/Cargo.toml

This will allow `cargo license` to work properly in the future.

Add licenses to all Cargo.toml files

---

audio/Cargo.toml
servo-media-derive/Cargo.toml

This is the only servo media package that uses underscores in the name
when all the others use dashes.

Rename `servo_media_derive` to `servo-media-derive`

---

Cargo.lock
audio/Cargo.toml
audio/decoder.rs
audio/lib.rs
audio/node.rs
backends/dummy/Cargo.toml
backends/dummy/lib.rs
backends/gstreamer/Cargo.toml
backends/gstreamer/webrtc.rs
examples/simple_webrtc.rs
servo-media-derive/lib.rs
webrtc/Cargo.toml
webrtc/lib.rs
webrtc/thread.rs

This is no longer necessary in modern versions of Rust and the library
is now unmaintained. See
https://blog.rust-lang.org/2019/05/23/Rust-1.35.0.html#fn-closure-traits-implemented-for-box%3Cdyn-fn*%3E

Stop using the `boxfnonce` library

---

backends/gstreamer/audio_decoder.rs
backends/gstreamer/audio_sink.rs
backends/gstreamer/audio_stream_reader.rs
backends/gstreamer/player.rs
backends/gstreamer/render-android/lib.rs
backends/gstreamer/render-unix/lib.rs
backends/gstreamer/render.rs
backends/gstreamer/webrtc.rs
examples/player/app.rs

This will improve diagnostics when things go wrong as the text of the
error will be included in the Servo media error as well.

Pass on formatted error messages

---

examples/player/app.rs
examples/player/context.rs

Looks like this was broken by my recent changes.

Fix `cargo check --all-features` build

---

backends/gstreamer/player.rs

In order to display the first frame of a video that doesn't autoplay we can use [preroll](https://gstreamer.freedesktop.org/documentation/additional/design/preroll.html?gi-language=c). This guarantees that when the video is in the state PAUSED it has at least one buffer ready, which we can send to the video renderer.
The closure from the `new_sample` callback has been extracted since the logic for rendering video samples and preroll samples is the same.
Fixes servo/servo#31666. A detailed log of the reasoning behind this change and an alternative implementation (which required a new api function so this one was favoured) can be found on that issue.

Render first video frame when preroll is available

---

audio/context.rs
audio/render_thread.rs
backends/dummy/lib.rs
backends/gstreamer/lib.rs
examples/muted_audiocontext.rs
examples/params_connect2.rs
examples/stream_reader_node.rs
servo-media/lib.rs

Part of https://github.com/servo/servo/issues/32986, in order to handle errors in Servo, we need to remove panics and return errors.

Handle errors from AudioRenderThread::start

---

Cargo.lock
Cargo.toml
backends/gstreamer/lib.rs
backends/gstreamer/player.rs
backends/gstreamer/source.rs

This is necessary to work around RUSTSEC-2024-0429, which affects glib version 0.20. (https://github.com/servo/servo/issues/34766)

Update gstreamer crates to 0.23

---

Cargo.lock
backends/gstreamer/Cargo.toml
streams/Cargo.toml
streams/lib.rs
streams/registry.rs
webrtc/Cargo.toml

The gstreamer/webrtc crates were depending
on lazy_static, but not using it.
In the case of the streams crate, lazy_static
can be replaced by the LazyLock struct from
the standard library.
(https://doc.rust-lang.org/std/sync/struct.LazyLock.html)

Remove dependency on `lazy_static`

---

backends/gstreamer/player.rs

Some seekable stream may not always have a duration so need to do validation
of "metadata.duration" before using it to calculate seekable time ranges.
Fixes: https://github.com/servo/servo/issues/36748
Fixes: https://github.com/servo/servo/issues/36809
Co-authored-by: Mitchel Stewart

seekable: Do validation of stream duration
