src/backends/gstreamer/audio_stream.rs
https://github.com/ferjm/media/pull/3#discussion_r186027319
=> Cleanup gstplayer leftover

src/backends/gstreamer/audio_sink.rs
=> Adjust appsrc caps rate to fix android example

examples/play.rs, src/audio/graph_thread.rs, src/audio/node.rs, src/audio/oscillator_node.rs, src/backends/gstreamer/audio_sink.rs, src/lib.rs
I'll be adding better support for channels and multiple input/output soon
r? @ferjm
=> Cleanup process()

src/audio/destination_node.rs, src/audio/graph_thread.rs, src/audio/mod.rs, src/audio/node.rs
=> DestinationNode placeholder

build.rs
=>  Do not download Android dependencies on every build 

examples/params.rs, examples/params_settarget.rs, examples/play.rs, examples/play_noise.rs, servo-media/src/audio/buffer_source_node.rs, servo-media/src/audio/destination_node.rs, servo-media/src/audio/graph.rs, servo-media/src/audio/graph_impl.rs, servo-media/src/audio/render_thread.rs
This uses the GraphImpl I wrote in #45
Seems to be working well.
=> Use new graph stuff!

examples/audio_decoder.rs, examples/play_noise.rs, servo-media/src/audio/block.rs, servo-media/src/audio/buffer_source_node.rs, servo-media/src/audio/channel_node.rs, servo-media/src/audio/node.rs, servo-media/src/audio/render_thread.rs
=> Support channels in AudioBuffer; clean up AudioBufferSourceNode; add ChannelMergerNode

examples/audio_decoder.rs, examples/channels.rs, examples/params.rs, examples/params_settarget.rs, examples/play.rs, examples/play_noise.rs, servo-media/src/audio/buffer_source_node.rs, servo-media/src/audio/gain_node.rs, servo-media/src/audio/macros.rs, servo-media/src/audio/node.rs, servo-media/src/audio/oscillator_node.rs, servo-media/src/audio/render_thread.rs
These are the two commits from #59 that were not related to the getters.
r? @Manishearth
=> Allow nodes to define message handlers by message type 

servo-media/src/audio/graph.rs
=> Add various disconnect() methods

servo-media/src/audio/oscillator_node.rs
This is mostly to support this commit https://github.com/ferjm/servo/commit/ac7b7ea977e0da2c42a87cffcc5db6f3dd58e64d and to allow us to run [the Violent Theremin](https://ferjm.github.io/violent-theremin/) demo :)
=> OscillatorNode SetDetune message

servo-media/src/audio/buffer_source_node.rs
=> Expose setters for AudioBufferSourceNode params

examples/audio_decoder.rs, examples/play_noise.rs, servo-media/src/audio/buffer_source_node.rs
=> Allow unsetting AudioBufferSourceNode buffer

Cargo.lock, servo-media/Cargo.toml
=> Update regex dep to 1.0 to match servo

servo-media/src/audio/node.rs, servo-media/src/audio/param.rs
=> Add SetParamRate message type

audio/src/block.rs, audio/src/buffer_source_node.rs, audio/src/channel_node.rs, audio/src/context.rs, audio/src/decoder.rs, audio/src/destination_node.rs, audio/src/gain_node.rs, audio/src/graph.rs, audio/src/lib.rs, audio/src/node.rs, audio/src/oscillator_node.rs, audio/src/param.rs, audio/src/render_thread.rs, backends/gstreamer/src/audio_decoder.rs, backends/gstreamer/src/audio_sink.rs, backends/gstreamer/src/lib.rs, examples/android/lib/src/lib.rs, examples/audio_decoder.rs, examples/channels.rs, examples/channelsum.rs, examples/params.rs, examples/params_settarget.rs, examples/play.rs, examples/play_noise.rs, servo-media-derive/src/lib.rs, servo-media/src/lib.rs
https://webaudio.github.io/web-audio-api/#dom-audioscheduledsourcenode-onended
r? @Manishearth
=> Add support for the AudioScheduledSourceNode.ended event

audio/src/buffer_source_node.rs
=> Fix index out of bounds panic during audio buffer source processing

audio/src/graph.rs, audio/src/oscillator_node.rs, examples/params_connect2.rs
This was a bit buggy
r? @ferjm
=> Fix processing of params for oscillator nodes

audio/src/block.rs, audio/src/offline_sink.rs
=> Push silence to offline sink if nothing reaches the output

audio/src/context.rs, audio/src/destination_node.rs, audio/src/graph.rs, audio/src/node.rs, audio/src/render_thread.rs
Otherwise we will crash for offline contexts with > 2 channels
r? @ferjm
=> Set channel count for destination node in offline audio context

backends/gstreamer/src/audio_decoder.rs
=> Improve audio decoder performance by making sink process samples asap

audio/src/node.rs, audio/src/panner_node.rs
=> Add PannerNode field setters

audio/src/panner_node.rs
It's clamped below 1 for linear distance models. We can't actually clamp the stored value
since the distance model may change again, so we clamp it during processing.
r? @ferjm
=> Clamp rolloff_factor

Cargo.lock, backends/gstreamer/Cargo.toml, examples/Cargo.toml, player/Cargo.toml
In the light of https://github.com/servo/servo/pull/21325#issuecomment-416578365
=> Update ipc-channel to 0.11

backends/gstreamer/src/player.rs, player/src/lib.rs
=> player: add pause method

Cargo.lock, audio/src/buffer_source_node.rs
We need this to fix an [AudioBuffer WPT crash](https://github.com/servo/servo/blob/master/tests/wpt/metadata/webaudio/the-audio-api/the-audiobuffer-interface/audiobuffer-copy-channel.html.ini)
=>  Expose getter for AudioBuffer mutable channel data 

backends/gstreamer/build.rs, servo-media/Cargo.toml, servo-media/src/lib.rs
This is required for https://github.com/servo/servo/pull/21730
r? @Manishearth
=> Enable Gstreamer backend for Android

audio/src/destination_node.rs
Minor fix, handles https://github.com/servo/servo/issues/21925
=> Allow AudioDestinationNodes to set channel count mode

.travis.yml, README.md, etc/android_bootstrap.sh, examples/android/build.sh, examples/android/run.sh
=> Add android configuration to TravisCI

backends/gstreamer/src/player.rs
https://github.com/servo/servo/issues/22010#issuecomment-432599657
=> Workaround set player uri bug

backends/gstreamer/src/player.rs, player/src/lib.rs
Related with [servo/servo#22292](https://github.com/servo/servo/issues/22292)
=> Adding support for set_volume to the trait Player

examples/simple_player.rs
We were previously expecting only the two seek requests manually triggered from the tests, but we may receive additional random seek requests from the Player, so lets make sure that we are able to handle any number of seek requests.
=> Allow simple_player example to perform random seeks

backends/gstreamer/src/player.rs, player/src/lib.rs
=> Expose `set_mute` method on Player Trait

.travis.yml
Regenerating a new GStreamer 1.14 bundle with a recent GLib (2.48)
=> Downgrade travis distro to trusty

backends/gstreamer/src/audio_decoder.rs, backends/gstreamer/src/player.rs
After Sebastian's recommendation in the IRC.
=> Don't cast gobject to pass to set_property

Cargo.lock, Cargo.toml, backends/gstreamer-gl-egl/Cargo.toml, backends/gstreamer-gl-egl/src/lib.rs, backends/gstreamer/Cargo.toml, backends/gstreamer/src/lib.rs, backends/gstreamer/src/player.rs
This should unblock updating servo-media in Servo while we work on a different workaround for the [existing build issues](https://github.com/servo/servo/pull/22944#issuecomment-468827665).
=> Temporarily disable GL functionality

backends/gstreamer/lib.rs, backends/gstreamer/player.rs
=> Ignore seek data requests if player is not ready to consume data

audio/offline_sink.rs, audio/param.rs, backends/gstreamer/render-unix/lib.rs, examples/player/ui.rs
[ ] remove spurious variable mutability labels
[ ] have just one PlayerGLContext implementation in player test app
=> Minor clean ups

examples/stereo_panner.rs
Otherwise this example panics.
=> Send panning message to stereo panner node.

audio/oscillator_node.rs
=> Make sure oscillator nodes receive start messages

backends/gstreamer/lib.rs
AcqRel doesn't mean "pick one based on your operation", turns out
r? @jdm
=> Use Acquire/Release ordering

.travis.yml
=> Use xenial for CI

Cargo.lock, backends/gstreamer/lib.rs, examples/Cargo.toml, examples/player/main.rs, examples/player/player_wrapper.rs, examples/player/ui.rs, examples/simple_webrtc.rs, servo-media/lib.rs
In order to avoid stepping on each other's toes, I send this pull request with a couple patches that clean up a bit our code, which I keep in under my working branches :)
=> code clean-ups

backends/gstreamer/player.rs
Background is in https://github.com/servo/servo/issues/23705#issuecomment-510127043 and https://github.com/servo/media/issues/282. With this change I'm able to play various pieces of media in both UWP and desktop Servo builds.
=> Disable progressive downloading on Windows.

Cargo.lock, backends/gstreamer/player.rs, backends/gstreamer/render-unix/lib.rs, backends/gstreamer/render.rs, backends/gstreamer/render/lib.rs, examples/Cargo.toml, examples/player/renderer.rs, player/frame.rs
=> Handling external OES textures

Cargo.lock, backends/gstreamer/render-unix/Cargo.toml, examples/Cargo.toml, examples/player/app.rs, examples/player/main.rs
Mainly, this PR does an upgrade to gstreamer-rs 0.14.5, and a few clean ups.
=> Build updates

backends/gstreamer/Cargo.toml
=> fix configuration for android

backends/gstreamer/player.rs, player/metadata.rs
This is required for https://github.com/servo/servo/issues/24172
=> Add title to player metadata

backends/gstreamer/player.rs
This fixes https://github.com/servo/servo/issues/24413
=> Disable progressive downloading on Android

backends/gstreamer/audio_decoder.rs
These changes address the linking failure present in https://github.com/servo/servo/issues/24803. The mix-matrix it is the part I'm least confident about; the channel mask for the decodebin is reported as 0x000000000000003f and the one for the audioconvert element is 0x0000000000000000, and https://gstreamer.freedesktop.org/documentation/audioconvert/index.html?gi-language=c mentions "A mix matrix can be passed to audioconvert, that will govern the remapping of input to output channels." along with "If an empty mix matrix is specified, a (potentially truncated) identity matrix will be generated." and has examples of using an empty one.
=> Support audio decoders for inputs with unusual numbers of channels.

Cargo.lock, backends/gstreamer/Cargo.toml, backends/gstreamer/audio_decoder.rs, backends/gstreamer/audio_sink.rs, backends/gstreamer/media_capture.rs, backends/gstreamer/media_stream_source.rs, backends/gstreamer/player.rs, backends/gstreamer/registry_scanner.rs, backends/gstreamer/render-android/Cargo.toml, backends/gstreamer/render-android/lib.rs, backends/gstreamer/render-unix/Cargo.toml, backends/gstreamer/render-unix/lib.rs, backends/gstreamer/render.rs, backends/gstreamer/render/Cargo.toml, backends/gstreamer/webrtc.rs, examples/media_element_source_node.rs, examples/muted_player.rs, examples/simple_player.rs
=> Upgrade to gstreamer-rs 0.15

audio/context.rs, backends/gstreamer/lib.rs, servo-media/lib.rs, streams/registry.rs
im not sure how to do this with lazy_static since init requires type parameter
but at least this addresses null pointer dereference
issue at hand: #306
=> return err if ServoMedia wasnt initialized

audio/buffer_source_node.rs
fixes https://github.com/servo/servo/issues/26663
=> fixed BufferSourceNode interpolation when pos is zero

audio/media_stream_destination_node.rs, audio/node.rs, audio/offline_sink.rs, audio/render_thread.rs, audio/sink.rs, backends/dummy/lib.rs, backends/gstreamer/audio_sink.rs, backends/gstreamer/lib.rs, backends/gstreamer/media_stream.rs, examples/stream_dest_node.rs, servo-media/lib.rs, streams/lib.rs
This helps avoid extra synchronization in MediaStreamDestinationNode
Fixes #351
=> Add MediaSocket for creating disconnected media streams

Cargo.lock, audio/block.rs, audio/context.rs, audio/lib.rs, audio/media_stream_source_node.rs, audio/node.rs, audio/render_thread.rs, backends/dummy/lib.rs, backends/gstreamer/audio_stream_reader.rs, backends/gstreamer/lib.rs, examples/Cargo.toml, examples/audioinput_stream.rs, examples/stream_reader_node.rs, examples/videoinput_stream.rs
<s>There's a gst-rs bug that causes this to spew some stuff to the console right now.</s> Introduced a hack as suggested by Sebastian.
Also I can't get audio capture to work but it *seems* like audio capture might be broken in general on my Linux machine.
Fixes https://github.com/servo/media/issues/343
=> Implement MediaStreamSourceNode

backends/gstreamer/webrtc.rs
This commit was supposed to be part of #364, but it seems that Github had service issues and lost the last commit :\
=> Do not register channel with buffered closed event

.travis.yml, etc/android_bootstrap.sh, etc/ubuntu_trusty_bootstrap.sh
=> Update s3 bucket.

docs/avplayback.md
This is just a starting point as it is quite a high level description.
=> Documentation - a/v playback

Cargo.lock, audio/Cargo.toml, audio/graph.rs
Part of <https://github.com/servo/servo/issues/24830>
=> chore(deps): bump `smallvec` from `^0.6` to `^1`

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, examples/Cargo.toml, examples/player/app.rs, examples/player/renderer.rs
Hopefully upgrading WebRender to the same version as Servo here will fix the problems with the examples.
=> Try to reenable the examples in the CI

.github/workflows/rust.yml
Instead of using GST_PLUGIN_FEATURE_RANK, which may not be supported by
our version of Gstreamer start a dummy jackd instance.
=> Try to fix the CI by using a dummy jack device

Cargo.toml, backends/gstreamer/Cargo.toml, backends/gstreamer/render-android/Cargo.toml, backends/gstreamer/render-unix/Cargo.toml, backends/gstreamer/render/Cargo.toml
This will make it easier to upgrade GStreamer in the future.
=> Start moving toward workspace dependencies

.github/workflows/rust.yml, backends/gstreamer/lib.rs, examples/audio_decoder.rs, examples/biquad.rs, examples/channels.rs, examples/channelsum.rs, examples/constant_source.rs, examples/iir_filter.rs, examples/media_element_source_node.rs, examples/muted_audiocontext.rs, examples/offline_context.rs, examples/oscillator.rs, examples/panner.rs, examples/params.rs, examples/params_connect.rs, examples/params_connect2.rs, examples/params_settarget.rs, examples/play.rs, examples/play_noise.rs, examples/set_value_curve.rs, examples/stereo_panner.rs, examples/stream_dest_node.rs, examples/stream_reader_node.rs, examples/wave_shaper.rs
This copies the result task from https://github.com/servo/ipc-channel/blob/main/.github/workflows/main.yml so we don't keep merging code that fails to build, then fixes the existing build errors.
=> Fix busted CI.

backends/gstreamer/lib.rs
I accidentally added this during https://github.com/servo/media/pull/429
=> Remove accidental println! statement

backends/ohos/Cargo.toml, backends/ohos/lib.rs, backends/ohos/player.rs
As a starting point for https://github.com/servo/media/issues/443. This PR add initial Backend Init logic that is mutual to all backend implementing `Backend` Trait. 
cc @jschwe @jdm @xiaochengh
=> initial stub for ohos backend
